### ISSUE TITLE
0.41.2-canary.2 route manifest runtime errors

### ISSUE THREAD

**Issue by beerose** [blitz-js/legacy-framework#222]
### What is the problem?

After creating a new Blitz app and running dev server, I'm facing an error: `TypeError: next_stdlib__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function`.

It happens with the latest canary version (0.41.2—canary.2) and works fine with the previous one (0.41.2-canary.1).

It also happens with `blitz build`.

`blitz codegen` doesn't fix the issue.

### Paste all your error logs here:

```
TypeError: next_stdlib__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function
```

### Paste all relevant code snippets here:

n/a

### What are detailed steps to reproduce this?

1. Install latest version (0.41.2—canary.2)
2. Create new project `blitz new test-app`
3. Run `yarn dev`
4. Go to your browser to see the error.

Alternatively, you can run `yarn build`.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.6

blitz: 0.41.2-canary.2 (global)

  Package manager: npm
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 32.44 MB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="1081" alt="Screenshot 2021-10-20 at 14 07 27" src="https://user-images.githubusercontent.com/9019397/138089758-f9e608c5-120e-48a9-a62d-2d4edcab9cb4.png">
