### ISSUE TITLE
0.38.0 errors: Can't resolve 'fs' and Cannot find module 'build-manifest.json'

### ISSUE THREAD

**Issue by acornellier** [blitz-js/legacy-framework#83]
### What is the problem?

After upgrading from 0.36.4 to 0.38.0, I get two errors when running the app. I didn't see these errors in 0.37.0 either.
I tried clearing .next, .blitz, and node_modules.

### Paste all your error logs here:

```
error - ../../node_modules/@blitzjs/core/server/dist/blitzjs-core-server.esm.js:6:0
Module not found: Can't resolve 'fs'
null
```

```
Error: Cannot find module '/Users/acornellier/git/Leaflet/.next/build-manifest.json'
Require stack:
- /Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/load-components.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/api-utils.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/server/next.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/server/lib/start-server.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/cli/next-dev.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/bin/next
- /Users/acornellier/git/Leaflet/node_modules/@blitzjs/server/bin/next-patched
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/Users/acornellier/git/Leaflet/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadComponents (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/load-components.js:1:1557)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.findPageComponents (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js:77:257)
    at async DevServer.renderErrorToHTML (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js:139:266) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/server/next.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/server/lib/start-server.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/cli/next-dev.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/bin/next',
    '/Users/acornellier/git/Leaflet/node_modules/@blitzjs/server/bin/next-patched'
  ]
}
```

### Paste all relevant code snippets here:

blitz.config.ts
```ts
import type { BlitzConfig } from "blitz"
import type { Ctx } from "@blitzjs/core/dist/declarations/types"
import type { ImageConfig } from "next/dist/next-server/server/image-config"
import { sessionMiddleware } from "blitz"

const isAuthorized = ({ ctx: { session }, args }: { ctx: Ctx; args: any }) => {
  const requirements = args[0]
  if (!requirements) return true

  const { roles: requiredRoles, userId: requiredUserId } = requirements

  if (
    requiredRoles &&
    !session.roles!.some((role) => requiredRoles.includes(role))
  ) {
    return false
  }

  if (
    requiredUserId !== undefined &&
    session.userId !== requiredUserId &&
    !(session.adminMode && session.roles!.some((role) => role === `ADMIN`))
  ) {
    return false
  }

  return true
}

const withBundleAnalyzer = require(`@next/bundle-analyzer`)({
  enabled: process.env.ANALYZE === `true`,
})

const config: BlitzConfig & { images: Partial<ImageConfig> } = {
  experimental: {
    reactRoot: false,
  },
  middleware: [
    sessionMiddleware({
      isAuthorized,
    }),
  ],
  images: {
    domains: [`storage.googleapis.com`, `cdn.fakercloud.com`],
  },
  // eslint-disable-next-line require-await
  async headers() {
    return [
      {
        source: `/:all*(svg|jpg|png|gif)`,
        locale: false,
        headers: [
          {
            key: `Cache-Control`,
            value: `public, max-age=9999999999, must-revalidate`,
          },
        ],
      },
    ]
  },
}

module.exports = withBundleAnalyzer(config)
```

### What are detailed steps to reproduce this?

unsure how to reproduce outside my app

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.38.0 (global)
blitz: 0.38.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 641.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/905_1623504293574/bin/node
    Yarn: 1.22.10 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/905_1623504293574/bin/yarn
    npm: 7.12.0 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/905_1623504293574/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1
    blitz: 0.38.0 => 0.38.0
    prisma: 2.25.0 => 2.25.0
    react: alpha => 18.0.0-alpha-43f4cc160
    react-dom: alpha => 18.0.0-alpha-43f4cc160
    typescript: 4.3.3 => 4.3.3
```
