### ISSUE TITLE
Upgrading to 0.15.1 breaks `blitz start` for existing projects. @blitzjs/cli: Cannot find module 'react'

### ISSUE THREAD

**Issue by simonedelmann** [blitz-js/legacy-framework#921]
### What is the problem?

When I upgraded to 0.15.1 (from 0.14.0), `blitz start` stops working and only shows a big error.

<details>
  <summary>Error Message</summary>

```
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/build.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/db.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/console.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/db.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/start.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(node:9456) TypeError Plugin: @blitzjs/cli: Cannot read property 'dim' of undefined
module: @oclif/config@1.15.1
task: runHook command_not_found
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
 ›   Error: command start not found
```  
</details>

This only happens if the blitz project is based on npm (`package-lock.json`) and not yarn (`yarn.lock`).

### Steps to Reproduce

1. Make sure yarn is **not** installed
2. Update to last version (0.15.1) of blitz: `npm install -g blitz`
3. Create new project `blitz new foo; cd foo`
4. Try to start the server `blitz start`

### Versions

```
debug: global
debug: pkgPath: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.4.0

blitz: 0.15.1 (global)
```

Edit: This also happens on 0.15.0, but **not** on 0.14.2-canary.0, so the error has to be https://github.com/blitz-js/blitz/compare/v0.14.2-canary.0...v0.15.0
